name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        java: [ '17' ]
        os: [ 'ubuntu-latest' ]
        jdk: [ 'zulu', 'microsoft', 'temurin' ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: ${{ matrix.jdk }}
        cache: 'maven'
    - name: Build
      run: mvn --no-snapshot-updates --no-transfer-progress -B clean package
